sudo: required
dist: trusty
language: java

matrix:
  include:
    - os: linux
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk10
  - openjdk11  

before_install:
  - sudo apt-get update

install:
  - ls .
  - ls **/*

script:
  - pwd
  - ./script.sh
  

notifications:
  email: false
